# Generated by Django 2.2.2 on 2019-06-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190612_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('descriptions', models.CharField(default='S', max_length=100)),
                ('address', models.CharField(default='Noida IN', max_length=100)),
                ('email', models.CharField(default='altf4upenter@gmail.com', max_length=100)),
                ('phone', models.CharField(default='9910741462', max_length=100)),
            ],
        ),
    ]
