# Generated by Django 2.2.2 on 2019-06-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190613_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('logo', models.ImageField(upload_to='project/')),
                ('descriptions', models.CharField(default='Descriptions', max_length=100)),
            ],
        ),
    ]
