# Generated by Django 2.2.2 on 2019-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('descriptions', models.CharField(default='Descriptions', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='logo',
            field=models.ImageField(upload_to='logo/'),
        ),
    ]
