# Generated by Django 2.2.2 on 2019-06-13 14:56

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190613_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cv',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='member',
            name='fixedpayrate',
            field=models.CharField(default='$0', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='payratehourly',
            field=models.CharField(default='$0', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='payratemonthly',
            field=models.CharField(default='$0', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='Software Developer', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='subjects',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=None, max_length=120, size=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(default='Not available', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='descriptions',
            field=models.CharField(default='Description not available', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(default='Not available', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default='Not available', max_length=100),
        ),
    ]
