# Generated by Django 2.2.2 on 2019-06-13 15:08

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190613_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='fixedpayrate',
        ),
        migrations.AlterField(
            model_name='member',
            name='cv',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='subjects',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=120, size=10),
        ),
    ]
