# Generated by Django 2.2.2 on 2019-06-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190614_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='weblink',
            field=models.URLField(blank=True),
        ),
    ]
