# Generated by Django 2.2.2 on 2019-06-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_projects_weblink'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
