# Generated by Django 2.2.2 on 2019-06-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepage_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='facebook_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='specialize',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
